version: '3.3'
services:

  mysql:
    image: mysql:5.7
    container_name: my_sql
    volumes:
       - ./deploy_structure.sql:/docker-entrypoint-initdb.d/deploy_structure.sql
       - ./data:/var/lib/mysql
    environment:
        MYSQL_DATABASE: deploy_db
        MYSQL_ROOT_PASSWORD: admin
    ports:
        - "3306:3306"
  application:
      depends_on:
        - mysql
      build: .
      ports:
        - "5000:5000"
      restart: always
      environment:
        DB_HOST: mysql:3306
        DB_USER: root
        DB_PASS: admin
        DB_SCHEMA: deploy_db
        APP_USER: teste
        APP_PASS: 123456
